### ISSUE TITLE
adding another detection layer on conv3_3

### ISSUE THREAD

**Issue by loackerc** [mahyarnajibi/SSH#28]
Dear @mahyarnajibi and @po0ya, I was wondering if during implementation, have you guys experimented adding another detection layer at conv3_3 which has feat_stride: 4? Since wider face consists a lot of small faces. If yes, could you please share some insights? many many thanks.

**Comment by po0ya** [comment]
Hey,
feat_stride: 4 requires a higher resolution feature map than conv4_3, else
we will be predicting two different values from the same location. Since
conv4_3 feature map dimensions are 1/8 of the input's.

Maybe a new module on conv3_3. I think we tried it and it didn't make that
much of a difference. It's worthwhile to do an analysis to see what is
"recall vs size" of the smallest scale detection module for gt boxes with
dim less than 8 with and without the new module.
