### ISSUE TITLE
demo.py crashes

### ISSUE THREAD

**Issue by siebenkopf** [mahyarnajibi/SSH#6]
After following your installation procedure, I tried to run `python demo.py`. Unfortunately, this crashes with the following error:
```
#################### Configuration ####################
USE_GPU_NMS:  True
DATA_DIR:  ./SSH/data
GPU_ID:  0
EPS:  1e-14
DEBUG:  False
MATLAB:  matlab
TEST{
    NMS_THRESH:  0.3
    SCALES:  [500, 800, 1200, 1600]
    ANCHOR_MIN_SIZE:  0
    N_DETS_PER_MODULE:  1000
    PYRAMID_BASE_SIZE:  [800, 1200]
    ORIG_SIZE:  False
    MAX_SIZE:  -1
}
ROOT_DIR:  ./SSH
EXP_DIR:  ssh_pyramid
PIXEL_MEANS:  [[[ 102.9801  115.9465  122.7717]]]
RNG_SEED:  3
#######################################################
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1031 11:13:32.679569  2292 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W1031 11:13:32.679675  2292 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W1031 11:13:32.679689  2292 _caffe.cpp:142] Net('SSH/models/test_ssh.prototxt', 1, weights='data/SSH_models/SSH.caffemodel')
I1031 11:13:32.685971  2292 upgrade_proto.cpp:67] Attempting to upgrade input file specified using deprecated input fields: SSH/models/test_ssh.prototxt
I1031 11:13:32.686033  2292 upgrade_proto.cpp:70] Successfully upgraded file specified using deprecated input fields.
W1031 11:13:32.686048  2292 upgrade_proto.cpp:72] Note that future Caffe releases will only support input layers and not input fields.
I1031 11:13:32.687358  2292 net.cpp:51] Initializing net from parameters: 
name: "SSH"
state {
  phase: TEST
  level: 0
}
... 
I1031 11:13:33.332159  2292 net.cpp:200] input does not need backward computation.
I1031 11:13:33.332171  2292 net.cpp:242] This network produces output ssh_boxes
I1031 11:13:33.332183  2292 net.cpp:242] This network produces output ssh_cls_prob
I1031 11:13:33.332281  2292 net.cpp:255] Network initialization done.
I1031 11:13:33.457337  2292 net.cpp:744] Ignoring source layer ssh_cls_score
Loading the network...Done!
F1031 11:13:34.977154  2292 blob.cpp:37] Check failed: shape[i] <= 2147483647 / count_ (2400 vs. 2333) blob size exceeds INT_MAX
*** Check failure stack trace: ***
Aborted (core dumped)
```

Can you reproduce this error?

**Comment by po0ya** [comment]
Please use the provided caffe of this repository for running this code. The
provided caffe has a 64bit compile flag which is needed for running SSH.

**Comment by siebenkopf** [comment]
I checked my `cmake` cache, and the only variable that I could find regarding 64 bit is `CUDA_64_BIT_DEVICE_CODE`, which is `ON`. Could you please let me know, how to enable the 64bit compile flag that you are mentioning?

**Comment by mahyarnajibi** [comment]
Did you clone and compile the following caffe repository?
github.com/mahyarnajibi/caffe-ssh

**Comment by po0ya** [comment]
You should use the provided makefile to compile that caffe. I'm not aware
of the exact cmake flagthat should be set to enable that feature.

**Comment by siebenkopf** [comment]
@mahyarnajibi Yes, I am using the caffe from that repository.

@po0ya I don't think that I want to switch back to the raw `Makefile`. I am running in a lab where I don't want to install your caffe version globally, and where I have to add more parameters to the `cmake` command line, such as installation directory, path for different libraries and so on.

Incorporating that flag into the `CMakeLists.txt` (if it does not exist yet) should not be that difficult. Maybe you can give it a try.

**Comment by siebenkopf** [comment]
My problem is that I don't know all the paths. `cmake` will automatically detect everything for me. Why should I worry about these paths if I don't need to. After learning cmake, I will never go back to the old times when I had to hack makefiles myself.

Anyways, I found a work-around. After searching for the according compiler flag, I set that flag by hand and then use cmake:
```
$ export CXXFLAGS="-DUSE_INDEX_64=1"
$ cmake <...>
$ make install
```

This worked. 

You might want to add a flag for this in the cmake configuration files. You might also ignore this feature request and close this issue. I leave my solution here, in case other people have the same issue.

**Comment by liangzimei** [comment]
hello , @mahyarnajibi @po0ya i also encounter this error. i follow your  steps, this is my Makefile.config, can you give some advices?
`## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

 USE_INDEX_64 := 1 
# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1
 USE_CUDNN := 1
# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# uncomment to disable IO dependencies and corresponding data layers
# USE_OPENCV := 0
 USE_OPENCV := 1
# USE_LEVELDB := 0
# USE_LMDB := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
 OPENCV_VERSION := 3
# OPENCV_VERSION := 3.2.0

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := open
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas
BLAS_INCLUDE := /usr/local/OpenBLAS/include
BLAS_LIB := /usr/local/OpenBLAS/lib
# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
 MATLAB_DIR := /usr/local/matlab/2014a
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
 PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
# ANACONDA_HOME := $(HOME)/anaconda2
# PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python2.7 \
		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include

# Uncomment to use Python 3 (default is Python 2)
# PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
 PYTHON_LIB := /usr/lib
# PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
# WITH_PYTHON_LAYER := 1
 WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include \
                /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib \
                /usr/lib/x86_64-linux-gnu/hdf5/serial

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# NCCL acceleration switch (uncomment to build with NCCL)
# https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
 USE_NCCL := 1

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @
`

**Comment by liangzimei** [comment]
hello , @mahyarnajibi @po0ya i also encounter this error. i follow your steps, this is my Makefile.config, can you give some advices?

## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

 USE_INDEX_64 := 1 
# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1
 USE_CUDNN := 1
# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# uncomment to disable IO dependencies and corresponding data layers
# USE_OPENCV := 0
 USE_OPENCV := 1
# USE_LEVELDB := 0
# USE_LMDB := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
 OPENCV_VERSION := 3
# OPENCV_VERSION := 3.2.0

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := open
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas
BLAS_INCLUDE := /usr/local/OpenBLAS/include
BLAS_LIB := /usr/local/OpenBLAS/lib
# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
 MATLAB_DIR := /usr/local/matlab/2014a
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
 PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
# ANACONDA_HOME := $(HOME)/anaconda2
# PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python2.7 \
		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include

# Uncomment to use Python 3 (default is Python 2)
# PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
 PYTHON_LIB := /usr/lib
# PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
# WITH_PYTHON_LAYER := 1
 WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include \
                /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib \
                /usr/lib/x86_64-linux-gnu/hdf5/serial

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# NCCL acceleration switch (uncomment to build with NCCL)
# https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
 USE_NCCL := 1

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @

**Comment by liangzimei** [comment]
hello , @mahyarnajibi @po0ya i also encounter this error. i follow your steps, this is my Makefile.config, can you give me some advices?

     # Refer to http://caffe.berkeleyvision.org/installation.html
     # Contributions simplifying and improving our build system are welcome!

     USE_INDEX_64 := 1 
     # cuDNN acceleration switch (uncomment to build with cuDNN).
     # USE_CUDNN := 1
     USE_CUDNN := 1
     # CPU-only switch (uncomment to build without GPU support).
     # CPU_ONLY := 1
   
     # uncomment to disable IO dependencies and corresponding data layers
     # USE_OPENCV := 0
     USE_OPENCV := 1
     # USE_LEVELDB := 0
     # USE_LMDB := 0
   
     # uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
     #	You should not set this flag if you will be reading LMDBs with any
     #	possibility of simultaneous read and write
     # ALLOW_LMDB_NOLOCK := 1
   
     # Uncomment if you're using OpenCV 3
     OPENCV_VERSION := 3
     # OPENCV_VERSION := 3.2.0
   
     # To customize your choice of compiler, uncomment and set the following.
     # N.B. the default for Linux is g++ and the default for OSX is clang++
     # CUSTOM_CXX := g++
   
     # CUDA directory contains bin/ and lib/ directories that we need.
     CUDA_DIR := /usr/local/cuda
     # On Ubuntu 14.04, if cuda tools are installed via
     # "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
     # CUDA_DIR := /usr
   
     # CUDA architecture setting: going with all of them.
     # For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
     # For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
     CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
   		-gencode arch=compute_20,code=sm_21 \
   		-gencode arch=compute_30,code=sm_30 \
   		-gencode arch=compute_35,code=sm_35 \
   		-gencode arch=compute_50,code=sm_50 \
   		-gencode arch=compute_52,code=sm_52 \
   		-gencode arch=compute_60,code=sm_60 \
   		-gencode arch=compute_61,code=sm_61 \
   		-gencode arch=compute_61,code=compute_61
   
      # BLAS choice:
      # atlas for ATLAS (default)
      # mkl for MKL
      # open for OpenBlas
      BLAS := open
      # Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
      # Leave commented to accept the defaults for your choice of BLAS
      # (which should work)!
      # BLAS_INCLUDE := /path/to/your/blas
      # BLAS_LIB := /path/to/your/blas
      BLAS_INCLUDE := /usr/local/OpenBLAS/include
      BLAS_LIB := /usr/local/OpenBLAS/lib
      # Homebrew puts openblas in a directory that is not on the standard search path
      # BLAS_INCLUDE := $(shell brew --prefix openblas)/include
      # BLAS_LIB := $(shell brew --prefix openblas)/lib
   
      # This is required only if you will compile the matlab interface.
      # MATLAB directory should contain the mex binary in /bin.
      MATLAB_DIR := /usr/local/matlab/2014a
      # MATLAB_DIR := /Applications/MATLAB_R2012b.app
   
      # NOTE: this is required only if you will compile the python interface.
      # We need to be able to find Python.h and numpy/arrayobject.h.
      PYTHON_INCLUDE := /usr/include/python2.7 \
   		/usr/lib/python2.7/dist-packages/numpy/core/include
      # Anaconda Python distribution is quite popular. Include path:
      # Verify anaconda location, sometimes it's in root.
      # ANACONDA_HOME := $(HOME)/anaconda2
      # PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
   		 $(ANACONDA_HOME)/include/python2.7 \
   		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include
   
      # Uncomment to use Python 3 (default is Python 2)
      # PYTHON_LIBRARIES := boost_python3 python3.5m
      # PYTHON_INCLUDE := /usr/include/python3.5m \
      #                 /usr/lib/python3.5/dist-packages/numpy/core/include
   
      # We need to be able to find libpythonX.X.so or .dylib.
      PYTHON_LIB := /usr/lib
      # PYTHON_LIB := $(ANACONDA_HOME)/lib
   
      # Homebrew installs numpy in a non standard path (keg only)
      # PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
      # PYTHON_LIB += $(shell brew --prefix numpy)/lib
   
      # Uncomment to support layers written in Python (will link against Python libs)
      # WITH_PYTHON_LAYER := 1
      WITH_PYTHON_LAYER := 1
   
      # Whatever else you find you need goes here.
      INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include \
                   /usr/include/hdf5/serial
      LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib \
                   /usr/lib/x86_64-linux-gnu/hdf5/serial
   
      # If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
      # INCLUDE_DIRS += $(shell brew --prefix)/include
      # LIBRARY_DIRS += $(shell brew --prefix)/lib
   
      # NCCL acceleration switch (uncomment to build with NCCL)
      # https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
      USE_NCCL := 1
   
      # Uncomment to use `pkg-config` to specify OpenCV library paths.
      # (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
      # USE_PKG_CONFIG := 1
   
      # N.B. both build and distribute dirs are cleared on `make clean`
      BUILD_DIR := build
      DISTRIBUTE_DIR := distribute
    
      # Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
      # DEBUG := 1
   
      # The ID of the GPU that 'make runtest' will use to run unit tests.
      TEST_GPUID := 0
   
      # enable pretty build (comment to see full commands)
      Q ?= @
